Numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [4]:
L = range(1000)
%timeit L2 = [i **2 for i in L]

45.3 μs ± 1.03 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
alist = [1,2,3,4,5,6]

In [8]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [9]:
blist = [1,2, , 4,5,6]

SyntaxError: invalid syntax (413037095.py, line 1)

In [10]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
ar1.dtype

dtype('int64')

In [13]:
ar2 = np.array([1.1, 2.2, 3.3])

In [14]:
print(ar2)

[1.1 2.2 3.3]


In [15]:
ar2.dtype

dtype('float64')

In [17]:
list_data = [1,2.,3]

ar3 = np.array(list_data, dtype="int")

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [19]:
np.array([1,2, np.nan ,4])

array([ 1.,  2., nan,  4.])

In [20]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [22]:
arr2 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [29]:
arr3 = arr2.reshape(2,-1,2)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [36]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [37]:
print(alist + 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [44]:
2 * a+b

array([12, 24, 36])

In [40]:
print(a == 2)

[False  True False]


In [41]:
a == 2

array([False,  True, False])

In [42]:
b > 10

array([False,  True,  True])

In [43]:
(a ==2) & (b > 10)

array([False,  True, False])

In [45]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [55]:
alist = [[0,1,2], [3,4,5]]
#pick 0,1,5



In [65]:
alist[:]

[[0, 1, 2], [3, 4, 5]]

In [68]:
alist[1][1:4]

[4, 5]

In [73]:
alist[0][:2]

[0, 1]

In [72]:
alist[0][1],alist[1][1]

(1, 4)

In [74]:
blist = np.array([[0,1,2],[3,4,5]])

In [75]:
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
blist[1][1],blist[0][1]

(np.int64(4), np.int64(1))

In [91]:
blist[:,1]

array([1, 4])

In [92]:
print(blist[[0,1],[1,1]])

[1 4]


In [118]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a[0:3,0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [145]:
a[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [147]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [148]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [151]:
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [153]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,1,1,1,1,2,2,2,2,])
a[idx]

array([11, 11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 33])

In [154]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
arr[0:2]

array([0, 1])

In [158]:
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [165]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [166]:
data = np.array([1,4,9,16])

In [167]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [168]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [169]:
np.mean(data)

np.float64(7.5)

In [170]:
np.std(data)

np.float64(5.678908345800274)

In [177]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [178]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [179]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [187]:
x[(x % 3 == 0) & (x % 4 == 1)]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [1]:
import numpy as np

In [2]:
x = np.arange(1,21)
x[(x%3 == 0) & (x%4 == 1)]

array([9])

In [5]:
! pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 4.1 MB/s eta 0:00:03
   - -------------------------------------- 0.5/11.3 MB 4.7 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/11.3 MB 5.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/11.3 MB 6.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.3 MB 7.3 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.3 MB 7.8 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.3 MB 7.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.8/11.3 MB 7.8 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/11.3 MB 8.1 MB/s eta 0:00:01
   ------------ --------------------------- 3.6/11.3 MB 8.0 MB/s eta 0:00:01
   ------------- -------------------------- 3.9/11.3 MB 7.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.3/11.3 MB 7.9 MB/s eta 0:00:01
   ---


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd

In [8]:
df = pd.read_csv("heroes.csv")
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+13
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [10]:
pd.options.display.float_format = '{:.0f}'.format

In [11]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [13]:
df.describe

<bound method NDFrame.describe of       이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000>

In [14]:
df.head()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [17]:
df["국적"].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [18]:
df["국적"].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [20]:
df["나이"].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [21]:
df.nlargest(7,"나이")

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [22]:
df.nlargest(7,"키")

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [25]:
df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [26]:
df.iloc,df.loc

(<pandas.core.indexing._iLocIndexer at 0x2517be92df0>,
 <pandas.core.indexing._LocIndexer at 0x2517be93c00>)

In [27]:
#df.iloc[ 행번호, 열번호]


In [28]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [29]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [32]:
df.iloc[[1,3,6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [33]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [34]:
df.loc[2:5]

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [38]:
df.loc[:2,["이름","직업"]]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [46]:
df[(df["키"]>180) & (df["나이"]<50)]

이름  나이     직업     국적    키         재산
1  토르  45      신  아스가르드  190        NaN
4  헐크  33  핵물리학자     미국  270 1000000000

In [52]:
df.loc[df["키"] >= 180,["이름","나이"]]

이름  나이
1  토르  45
4  헐크  33

In [53]:
df["전투력"] = 98

In [54]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   98
1     토르  45      신  아스가르드  190            NaN   98
2  스파이더맨  18   고등학생     미국  177            600   98
3   원더우먼  27     공주  데미스키라  178            NaN   98
4     헐크  33  핵물리학자     미국  270     1000000000   98
5   캡틴마블  25    파일럿     미국  170      340000000   98
6  블랙위도우  32    스파이    러시아  170       50000000   98

In [55]:
df["전투력"] = df["전투력"] - 5
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [60]:
df.drop(columns=["전투력"], inplace = True)

In [61]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [65]:
df["재산"].isnull().sum()

np.int64(2)

In [66]:
df[df["재산"].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [67]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [68]:
df.dropna()

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [69]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [71]:
df["재산"].fillna(df["재산"].mean())

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [72]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [81]:
df.fillna(method="ffill")

C:\Users\EL061\AppData\Local\Temp\ipykernel_1996\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [88]:
df

0   58
1   45
2   18
3   27
4   33
5   36
6   32
Name: 나이, dtype: float64

In [82]:
df.iloc[5,1] = np.nan
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [86]:
#캡마 결측지를 나이의 평균값으로 채워
df = df["나이"].fillna(df["나이"].mean())
df

KeyError: '나이'

In [85]:
df

0   58
1   45
2   18
3   27
4   33
5   36
6   32
Name: 나이, dtype: float64

In [87]:
df

0   58
1   45
2   18
3   27
4   33
5   36
6   32
Name: 나이, dtype: float64

In [89]:
df = pd.read_csv('heroes.csv')

In [90]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [91]:
df.iloc[5,1] = np.nan
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [92]:
df["나이"].mean()

np.float64(35.5)

In [97]:
df["나이"]=df["나이"].fillna(df["나이"].mean())

In [98]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 468.0+ bytes


In [100]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
#df.apply()
def add_cm(ki):
    return str(ki) + "cm"
    add("cm")

def remove_cm(b):
    part = b.replace("cmcm","")
    part_float = float(part)

    return
#df["키"].apply(add_cm)
df["키"]=df["키"].apply(lambda a: str(a)+"cm")
df


이름  나이     직업     국적      키             재산
0   아이언맨  58    CEO     미국  174cm 11500000000000
1     토르  45      신  아스가르드  190cm            NaN
2  스파이더맨  18   고등학생     미국  177cm            600
3   원더우먼  27     공주  데미스키라  178cm            NaN
4     헐크  33  핵물리학자     미국  270cm     1000000000
5   캡틴마블  36    파일럿     미국  170cm      340000000
6  블랙위도우  32    스파이    러시아  170cm       50000000

In [105]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [111]:
df.groupby("국적")["재산"].mean()

국적
데미스키라             NaN
러시아          50000000
미국      2875335000150
아스가르드             NaN
Name: 재산, dtype: float64